name: Playwright Python Tests (Manual Trigger by File)

on:
  workflow_dispatch:
    inputs:
      test_path:
        description: "Enter test file or folder to run (e.g., api_tests/test_api.py or api_tests/)"
        required: true
        default: "PWA_Test/"

jobs:
  test:
    runs-on: windows-latest
    name: Run Selected Playwright Tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-html playwright
          python -m playwright install --with-deps

      - name: Show project structure (for confirmation)
        run: |
          echo "Current directory: $(pwd)"
          ls -R

      - name: Run tests
        run: |
          echo "Running tests from path: ${{ github.event.inputs.test_path }}"
          export PYTHONPATH=$(pwd)       # Add repo root to Python path
          pytest ${{ github.event.inputs.test_path }} --maxfail=1 --disable-warnings -v --html=report.html


      - name: Upload HTML Test Report
        uses: actions/upload-artifact@v4
        with:
          name: Playwright-Test-Report
          path: report.html
